### ISSUE TITLE
Citation API input not visible after enter the data

### ISSUE THREAD

**Issue by zalamuia** [RBoelter/citations#3]
Installed Plugin to 3.2.1.2

Server Info
OS platform | Linux
PHP version | 7.2.17
Apache version | Apache/2.4.6 (CentOS)
Database driver | mysqli
Database server version | 5.5.60-MariaDB

After adding API key to the field  but it is not visible after save. 
Scopus API and CrossRef API not visible. Checked one by one by selection one by one by selecting top dropdown menu.

![citation](https://user-images.githubusercontent.com/61810595/101724085-a92c2b80-3ae8-11eb-98d5-255bc47e93d9.png)

However, I can get Google citation.
I am not sure this is common.

Thanks.
Zashirul

**Comment by RBoelter** [comment]
Hi, the key is saved if the input field has a blue border. The keys are hidden for security reasons because it is possible that several people have access to plug in settings. There is a hint in the text above these fields.

**Comment by RBoelter** [comment]
Google does not provide an API to get information from scholar, therefore it is not that easy to get citations from Google.
