### ISSUE TITLE
not working (OJS 3.1.2.4)

### ISSUE THREAD

**Issue by dionojs** [RBoelter/citations#4]
**Describe the bug**
The plugin is not working in our OJS 3.1.2.4 (see image below). Initially we thought this was due to the keys not being saved. But I checked https://github.com/RBoelter/citations/issues/3 and indeed the Crossref boxes are blue (we have put in the keys for this) and the Scopus keys are not (keys not used), so this seems to work as described.

However we get no response from the plugin. 
We tried selecting only crossref, only scopus, no scholar, no PMC ... nothing changes in the front end.

**What application are you using?**
OJS 3.1.2.4
Linux server, PHP 7.3.25

**Additional information**
Screenshot from front-end:
![image](https://user-images.githubusercontent.com/64978101/101871424-35435f00-3b8c-11eb-9509-829fd48b4090.png)

**Comment by RBoelter** [comment]
Hello,
this looks strange. I tested the plugin 5 minutes ago with OJS 3.1.2.4 and PHP 7.3.22 and it worked. I am wondering why the images are not loaded. What theme are you using? The plugin uses JavaScript to load the citations, it seems that the .css and .js files are not loaded.

**Comment by RBoelter** [comment]
The plugin inserts a `<script src="https://<your journal url>/plugins/generic/citations/js/citations.js?v=3.1.2.4" type="text/javascript">` at the end of the page before the closing '</body>' tag. Can you check if this script is included?

**Comment by dionojs** [comment]
using the default theme.

The script seems to be there

<script src="https://<journal site>/plugins/generic/citations/js/citations.js?v=3.1.2.4" type="text/javascript"></script>

it is placed before another script about pkpusagedata/stats and 
this:
<script type="text/javascript">
--
  | (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){
  | (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  | m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  | })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  |  
  | ga('create', 'UA-21806971-2', 'auto');
  | ga('send', 'pageview');
  | </script>

**Comment by dionojs** [comment]
when I try to visit directly the link of an image I get a Forbidden 403 message

**Comment by RBoelter** [comment]
It seems to be a problem with the folder permissions of your webserver, not with the plugin (403). It looks to me that your Apache server restricts access to the plugin folder.

**Comment by dionojs** [comment]
I will check with our host and get back to you.

**Comment by dionojs** [comment]
yeap, it was a permission thing, it works ok now
